services:
  - type: web
    name: agrocist-ivr
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AT_API_KEY
        sync: false
      - key: AT_USERNAME
        sync: false
      - key: AT_SHORT_CODE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379